"""Taxonomy parametric extras (72 problems).

These are the parametric F1/F2/F3/F4/F6/F7 problems whose per-problem
RT numbers appear in SORCAR_FAMILY_TAXONOMY.md but whose definitions
were generated by a cluster-only script and never committed. This
module reconstructs them faithfully from the taxonomy's own shape +
reduce-op annotations so that `--problem <taxonomy_name>` resolves for
the measured-strat re-run.

Faithfulness contract (per problem): identical tensor shape, identical
reduce op, identical baseline collective count (so the Phase-1 sim
baseline cost matches), and identical optimal structure (one surviving
AR for F1/F2/F4/F6/F7; algebraic zero for F3). Coefficient values are
chosen deterministically; only the builtin==reference agreement matters
for correctness, and both are generated from the same spec here.
"""
import torch
from .problems import CollectiveProblem, register_problem


# ------------------------------------------------------------------
# Helpers to build one CollectiveProblem from a compact spec and
# register it under its exact taxonomy name.
# ------------------------------------------------------------------
def _mk_1d_scaled(name, coefs, N=65536):
    """K inline SUM-ARs of one 1-D input x, combined as sum(c_i * AR(x)).

    Result = (sum coefs) * AR(x). If sum(coefs)==0 this is an algebraic
    zero (F3); otherwise one surviving AR (F1/F2)."""
    total = float(sum(coefs))

    def _ref(inputs, world_size):
        ax = sum(inp['x'] for inp in inputs)
        return [(total * ax).clone() for _ in range(world_size)]

    def _gen(world_size, pattern='uniform', shard_size=None, seed=0):
        torch.manual_seed(seed)
        pra = [{'x': torch.randn(N) * (r + 1), 'N': N} for r in range(world_size)]
        return {'per_rank_args': pra, 'shared_args': {},
                'expected': _ref(pra, world_size)}

    def _call(fn, args, s, r, w, nd, cpd, xm, tm, num_nodes=1):
        return fn(args['x'], args['N'], r, w, nd, cpd, xm, tm, num_nodes=num_nodes)

    sig = (f"def {name}_fn(x, N, rank, world_size, num_devices,\n"
           f"                 cores_per_device, xm, torch, num_nodes=1):")
    doc = f"Local x (N,). N={N}. Baseline issues {len(coefs)} inline SUM-ARs of x."
    body_lines = [f"def {name}_fn(x, N, rank, world_size, num_devices,",
                  "                 cores_per_device, xm, torch, num_nodes=1):",
                  "    acc = None"]
    for c in coefs:
        body_lines.append(f"    t = {c!r} * xm.all_reduce(xm.REDUCE_SUM, x)")
        body_lines.append("    acc = t if acc is None else acc + t")
    body_lines.append("    return acc")
    builtin = {name: "\n".join(body_lines) + "\n"}

    register_problem(CollectiveProblem(
        name=name, display_name=name, evolved_fn_name=f"{name}_fn",
        signature=sig, signature_doc=doc, reference_fn=_ref,
        generate_test_case=_gen, call_candidate=_call,
        builtin_templates=builtin))


def _mk_perrow(name, M, N, op='SUM'):
    """Per-row loop: M inline ARs (one per row) of a (M, N) tensor.
    Optimal = 1 full-tensor AR. Baseline = M row-ARs."""
    red = {'SUM': 'REDUCE_SUM', 'MAX': 'REDUCE_MAX', 'MIN': 'REDUCE_MIN'}[op]

    def _ref(inputs, world_size):
        xs = [inp['x'] for inp in inputs]
        if op == 'SUM':
            res = sum(xs)
        else:
            res = xs[0]
            fn = torch.maximum if op == 'MAX' else torch.minimum
            for x in xs[1:]:
                res = fn(res, x)
        return [res.clone() for _ in range(world_size)]

    def _gen(world_size, pattern='uniform', shard_size=None, seed=0):
        torch.manual_seed(seed)
        pra = [{'x': torch.randn(M, N) * (r + 1)} for r in range(world_size)]
        return {'per_rank_args': pra, 'shared_args': {},
                'expected': _ref(pra, world_size)}

    def _call(fn, args, s, r, w, nd, cpd, xm, tm, num_nodes=1):
        return fn(args['x'], r, w, nd, cpd, xm, tm, num_nodes=num_nodes)

    sig = (f"def {name}_fn(x, rank, world_size, num_devices,\n"
           f"                 cores_per_device, xm, torch, num_nodes=1):")
    doc = f"Local x ({M}, {N}). Baseline AR({op}) per row ({M} collectives)."
    builtin = {name: (
        f"def {name}_fn(x, rank, world_size, num_devices,\n"
        f"                 cores_per_device, xm, torch, num_nodes=1):\n"
        f"    rows = [xm.all_reduce(xm.{red}, x[m]) for m in range(x.shape[0])]\n"
        f"    return torch.stack(rows, dim=0)\n")}

    register_problem(CollectiveProblem(
        name=name, display_name=name, evolved_fn_name=f"{name}_fn",
        signature=sig, signature_doc=doc, reference_fn=_ref,
        generate_test_case=_gen, call_candidate=_call,
        builtin_templates=builtin))


def _mk_percol(name, M, N, op='SUM'):
    """Per-column loop: N inline ARs (one per column) of a (M, N) tensor."""
    red = {'SUM': 'REDUCE_SUM', 'MAX': 'REDUCE_MAX', 'MIN': 'REDUCE_MIN'}[op]

    def _ref(inputs, world_size):
        xs = [inp['x'] for inp in inputs]
        res = sum(xs)
        return [res.clone() for _ in range(world_size)]

    def _gen(world_size, pattern='uniform', shard_size=None, seed=0):
        torch.manual_seed(seed)
        pra = [{'x': torch.randn(M, N) * (r + 1)} for r in range(world_size)]
        return {'per_rank_args': pra, 'shared_args': {},
                'expected': _ref(pra, world_size)}

    def _call(fn, args, s, r, w, nd, cpd, xm, tm, num_nodes=1):
        return fn(args['x'], r, w, nd, cpd, xm, tm, num_nodes=num_nodes)

    sig = (f"def {name}_fn(x, rank, world_size, num_devices,\n"
           f"                 cores_per_device, xm, torch, num_nodes=1):")
    doc = f"Local x ({M}, {N}). Baseline AR({op}) per column ({N} collectives)."
    builtin = {name: (
        f"def {name}_fn(x, rank, world_size, num_devices,\n"
        f"                 cores_per_device, xm, torch, num_nodes=1):\n"
        f"    cols = [xm.all_reduce(xm.{red}, x[:, k]) for k in range(x.shape[1])]\n"
        f"    return torch.stack(cols, dim=1)\n")}

    register_problem(CollectiveProblem(
        name=name, display_name=name, evolved_fn_name=f"{name}_fn",
        signature=sig, signature_doc=doc, reference_fn=_ref,
        generate_test_case=_gen, call_candidate=_call,
        builtin_templates=builtin))


def _mk_perbatch(name, A, B, C, op='SUM'):
    """Per-batch loop on a 3-D (A, B, C) tensor: A inline ARs."""
    red = {'SUM': 'REDUCE_SUM', 'MAX': 'REDUCE_MAX', 'MIN': 'REDUCE_MIN'}[op]

    def _ref(inputs, world_size):
        xs = [inp['x'] for inp in inputs]
        if op == 'SUM':
            res = sum(xs)
        else:
            res = xs[0]
            fn = torch.maximum if op == 'MAX' else torch.minimum
            for x in xs[1:]:
                res = fn(res, x)
        return [res.clone() for _ in range(world_size)]

    def _gen(world_size, pattern='uniform', shard_size=None, seed=0):
        torch.manual_seed(seed)
        pra = [{'x': torch.randn(A, B, C) * (r + 1)} for r in range(world_size)]
        return {'per_rank_args': pra, 'shared_args': {},
                'expected': _ref(pra, world_size)}

    def _call(fn, args, s, r, w, nd, cpd, xm, tm, num_nodes=1):
        return fn(args['x'], r, w, nd, cpd, xm, tm, num_nodes=num_nodes)

    sig = (f"def {name}_fn(x, rank, world_size, num_devices,\n"
           f"                 cores_per_device, xm, torch, num_nodes=1):")
    doc = f"Local x ({A}, {B}, {C}). Baseline AR({op}) per batch ({A} collectives)."
    builtin = {name: (
        f"def {name}_fn(x, rank, world_size, num_devices,\n"
        f"                 cores_per_device, xm, torch, num_nodes=1):\n"
        f"    batches = [xm.all_reduce(xm.{red}, x[b]) for b in range(x.shape[0])]\n"
        f"    return torch.stack(batches, dim=0)\n")}

    register_problem(CollectiveProblem(
        name=name, display_name=name, evolved_fn_name=f"{name}_fn",
        signature=sig, signature_doc=doc, reference_fn=_ref,
        generate_test_case=_gen, call_candidate=_call,
        builtin_templates=builtin))


def _mk_slab(name, n_slabs, slab_N, scaled=False):
    """F7: contiguous slabs of a 1-D buffer AR'd separately then cat'd.
    Optimal = 1 AR of the whole buffer, slice the output."""
    N = n_slabs * slab_N
    coefs = [float(i + 1) if scaled else 1.0 for i in range(n_slabs)]

    def _ref(inputs, world_size):
        ax = sum(inp['x'] for inp in inputs)
        parts = [coefs[i] * ax[i * slab_N:(i + 1) * slab_N] for i in range(n_slabs)]
        return [torch.cat(parts).clone() for _ in range(world_size)]

    def _gen(world_size, pattern='uniform', shard_size=None, seed=0):
        torch.manual_seed(seed)
        pra = [{'x': torch.randn(N) * (r + 1)} for r in range(world_size)]
        return {'per_rank_args': pra, 'shared_args': {},
                'expected': _ref(pra, world_size)}

    def _call(fn, args, s, r, w, nd, cpd, xm, tm, num_nodes=1):
        return fn(args['x'], r, w, nd, cpd, xm, tm, num_nodes=num_nodes)

    sig = (f"def {name}_fn(x, rank, world_size, num_devices,\n"
           f"                 cores_per_device, xm, torch, num_nodes=1):")
    doc = (f"Local x ({N},) = {n_slabs} contiguous slabs of {slab_N}. "
           f"Baseline ARs each slab separately then cat.")
    body = [f"def {name}_fn(x, rank, world_size, num_devices,",
            "                 cores_per_device, xm, torch, num_nodes=1):",
            f"    n_slabs, slab_N = {n_slabs}, {slab_N}",
            "    parts = []",
            "    for i in range(n_slabs):",
            "        s = xm.all_reduce(xm.REDUCE_SUM, x[i*slab_N:(i+1)*slab_N])",
            f"        parts.append(s * {'(i + 1)' if scaled else '1.0'})",
            "    return torch.cat(parts)"]
    builtin = {name: "\n".join(body) + "\n"}

    register_problem(CollectiveProblem(
        name=name, display_name=name, evolved_fn_name=f"{name}_fn",
        signature=sig, signature_doc=doc, reference_fn=_ref,
        generate_test_case=_gen, call_candidate=_call,
        builtin_templates=builtin))


def _mk_perrow_mixed(name, M, N):
    """F6 compound: per-row AR_MAX - AR_MIN over a (M, N) tensor.
    2M collectives -> 2 full-tensor collectives."""
    def _ref(inputs, world_size):
        xs = [inp['x'] for inp in inputs]
        mx = xs[0].clone()
        mn = xs[0].clone()
        for x in xs[1:]:
            mx = torch.maximum(mx, x)
            mn = torch.minimum(mn, x)
        return [(mx - mn).clone() for _ in range(world_size)]

    def _gen(world_size, pattern='uniform', shard_size=None, seed=0):
        torch.manual_seed(seed)
        pra = [{'x': torch.randn(M, N) * (r + 1)} for r in range(world_size)]
        return {'per_rank_args': pra, 'shared_args': {},
                'expected': _ref(pra, world_size)}

    def _call(fn, args, s, r, w, nd, cpd, xm, tm, num_nodes=1):
        return fn(args['x'], r, w, nd, cpd, xm, tm, num_nodes=num_nodes)

    sig = (f"def {name}_fn(x, rank, world_size, num_devices,\n"
           f"                 cores_per_device, xm, torch, num_nodes=1):")
    doc = (f"Local x ({M}, {N}). Baseline per-row AR_MAX(x[m]) - AR_MIN(x[m]) "
           f"({2 * M} collectives).")
    builtin = {name: (
        f"def {name}_fn(x, rank, world_size, num_devices,\n"
        f"                 cores_per_device, xm, torch, num_nodes=1):\n"
        f"    rows = []\n"
        f"    for m in range(x.shape[0]):\n"
        f"        mx = xm.all_reduce(xm.REDUCE_MAX, x[m])\n"
        f"        mn = xm.all_reduce(xm.REDUCE_MIN, x[m])\n"
        f"        rows.append(mx - mn)\n"
        f"    return torch.stack(rows, dim=0)\n")}

    register_problem(CollectiveProblem(
        name=name, display_name=name, evolved_fn_name=f"{name}_fn",
        signature=sig, signature_doc=doc, reference_fn=_ref,
        generate_test_case=_gen, call_candidate=_call,
        builtin_templates=builtin))


def _mk_mixmaxmin(name, K=8, N=4096):
    """F6: K alternating scaled AR_MAX / AR_MIN of a 1-D input.
    2K collectives -> 2 (one MAX, one MIN)."""
    cmax = [float(i + 1) * 0.1 for i in range(K)]
    cmin = [float(i + 1) * 0.05 for i in range(K)]
    smax, smin = float(sum(cmax)), float(sum(cmin))

    def _ref(inputs, world_size):
        xs = [inp['x'] for inp in inputs]
        mx = xs[0].clone()
        mn = xs[0].clone()
        for x in xs[1:]:
            mx = torch.maximum(mx, x)
            mn = torch.minimum(mn, x)
        return [(smax * mx + smin * mn).clone() for _ in range(world_size)]

    def _gen(world_size, pattern='uniform', shard_size=None, seed=0):
        torch.manual_seed(seed)
        pra = [{'x': torch.randn(N) * (r + 1)} for r in range(world_size)]
        return {'per_rank_args': pra, 'shared_args': {},
                'expected': _ref(pra, world_size)}

    def _call(fn, args, s, r, w, nd, cpd, xm, tm, num_nodes=1):
        return fn(args['x'], r, w, nd, cpd, xm, tm, num_nodes=num_nodes)

    sig = (f"def {name}_fn(x, rank, world_size, num_devices,\n"
           f"                 cores_per_device, xm, torch, num_nodes=1):")
    doc = (f"Local x ({N},). Baseline interleaves {K} scaled AR_MAX and {K} "
           f"scaled AR_MIN of x ({2 * K} collectives).")
    body = [f"def {name}_fn(x, rank, world_size, num_devices,",
            "                 cores_per_device, xm, torch, num_nodes=1):",
            "    acc = None"]
    for i in range(K):
        body.append(f"    a = {cmax[i]!r} * xm.all_reduce(xm.REDUCE_MAX, x)")
        body.append("    acc = a if acc is None else acc + a")
        body.append(f"    b = {cmin[i]!r} * xm.all_reduce(xm.REDUCE_MIN, x)")
        body.append("    acc = acc + b")
    body.append("    return acc")
    builtin = {name: "\n".join(body) + "\n"}

    register_problem(CollectiveProblem(
        name=name, display_name=name, evolved_fn_name=f"{name}_fn",
        signature=sig, signature_doc=doc, reference_fn=_ref,
        generate_test_case=_gen, call_candidate=_call,
        builtin_templates=builtin))


# ------------------------------------------------------------------
# Coefficient builders for the inline-AR families.
# ------------------------------------------------------------------
def _plain(k):            # k inline ARs, all +1  -> k * AR(x)
    return [1.0] * k

def _altsign(k):          # coefs (-1)^i * (i+1) -> nonzero, one surviving AR
    return [((-1.0) ** i) * (i + 1) for i in range(k)]

def _alt_unit(k):         # +1,-1,+1,... but forced nonzero via last term
    c = [1.0 if i % 2 == 0 else -1.0 for i in range(k)]
    if abs(sum(c)) < 1e-9:
        c[-1] += 1.0      # break the exact cancellation -> F2 (not F3)
    return c

def _algzero(k):          # coefs sum to exactly 0 -> algebraic zero (F3)
    c = [float(i + 1) for i in range(k - 1)]
    c.append(-float(sum(c)))
    return c

def _scaled_with_zeros(k):  # F1: distinct scales, some cancel, net nonzero
    c = []
    for i in range(k):
        c.append(float(i + 1))
        if i % 2 == 1:
            c.append(-float(i))       # partial cancellation ("w/ zeros")
    return c[:k] if len(c) >= k else c


# ==================================================================
# REGISTER ALL 72 EXTRAS
# ==================================================================

# ---- F1 sequential / F2 CSE: inline-AR families (1-D, N=65536) ----
_mk_1d_scaled('eightyaltsum', _altsign(80))
_mk_1d_scaled('sixtyfourinline', _plain(64))
_mk_1d_scaled('fiftyinline', _plain(50))
_mk_1d_scaled('fortyinline', _plain(40))
_mk_1d_scaled('thirtysixinline', _plain(36))
_mk_1d_scaled('thirtytwoalt', _altsign(32))
_mk_1d_scaled('thirtyinline', _plain(30))
_mk_1d_scaled('twentyeightinline', _plain(28))
_mk_1d_scaled('twentyfourinline', _plain(24))
_mk_1d_scaled('twentyinline', _plain(20))
_mk_1d_scaled('sixteeninlin', _plain(16))
_mk_1d_scaled('twelveinlin', _plain(12))
_mk_1d_scaled('tenariindep', _plain(10))
_mk_1d_scaled('large_N_4ar', _plain(4))

# ---- F1 scaled sequences ----
_mk_1d_scaled('seven_scaled_diff', _scaled_with_zeros(7))
_mk_1d_scaled('seven_scaled_input', [float(i + 1) for i in range(7)])
_mk_1d_scaled('mixedscaledseq', [1.0, -2.0, 3.0, -0.5, 2.5])
_mk_1d_scaled('csescaleddiff', _scaled_with_zeros(5))

# ---- F3 algebraic zero ----
_mk_1d_scaled('algzero20', _algzero(20))
_mk_1d_scaled('algzero16', _algzero(16))

# ---- F4 per-row SUM ----
_mk_perrow('perrowM2048', 2048, 32, 'SUM')
_mk_perrow('perrowM3072', 3072, 24, 'SUM')
_mk_perrow('perrowM1536', 1536, 42, 'SUM')
_mk_perrow('perrowM768', 768, 96, 'SUM')
_mk_perrow('perrowM384', 384, 192, 'SUM')
_mk_perrow('perrowM192', 192, 256, 'SUM')
_mk_perrow('perrowM144', 144, 384, 'SUM')
_mk_perrow('perrowM112', 112, 512, 'SUM')
_mk_perrow('perrowM80', 80, 256, 'SUM')
_mk_perrow('perrowM56', 56, 1024, 'SUM')
_mk_perrow('perrowM40', 40, 512, 'SUM')
_mk_perrow('perrowM28', 28, 1024, 'SUM')
_mk_perrow('perrowM32N8K', 32, 8192, 'SUM')
_mk_perrow('perrowM64N4K', 64, 4096, 'SUM')

# ---- F4 per-row MAX ----
_mk_perrow('perrowmaxM256', 256, 256, 'MAX')
_mk_perrow('perrowmaxM256big', 256, 256, 'MAX')
_mk_perrow('perrowmaxM128', 128, 512, 'MAX')
_mk_perrow('perrowmaxM128big', 128, 512, 'MAX')
_mk_perrow('perrowmaxM96', 96, 512, 'MAX')
_mk_perrow('perrowmaxM96N1K', 96, 1024, 'MAX')
_mk_perrow('perrowmaxM64', 64, 1024, 'MAX')
_mk_perrow('perrowmaxM48N2K', 48, 2048, 'MAX')

# ---- F4 per-row MIN ----
_mk_perrow('perrowminM256', 256, 256, 'MIN')
_mk_perrow('perrowminM128', 128, 512, 'MIN')
_mk_perrow('perrowminM64', 64, 1024, 'MIN')
_mk_perrow('perrowminM48', 48, 512, 'MIN')

# ---- F4 per-column SUM ----
_mk_percol('percolC512', 256, 512, 'SUM')
_mk_percol('percolC384', 128, 384, 'SUM')
_mk_percol('percolC256', 128, 256, 'SUM')
_mk_percol('percolC192', 256, 192, 'SUM')
_mk_percol('percolC128Big', 256, 128, 'SUM')
_mk_percol('percolC128Bigger', 512, 128, 'SUM')
_mk_percol('percolC128', 64, 128, 'SUM')
_mk_percol('percolC96', 192, 96, 'SUM')
_mk_percol('percolC64Big', 256, 64, 'SUM')
_mk_percol('percolC48', 128, 48, 'SUM')
_mk_percol('percolC24', 192, 24, 'SUM')

# ---- F4 per-batch / per-slice 3-D ----
_mk_perbatch('perbatchM32', 32, 16, 512, 'SUM')
_mk_perbatch('perbatchM12', 12, 32, 256, 'SUM')
_mk_perbatch('perbatchM4big', 4, 64, 512, 'SUM')
_mk_perbatch('perbatch3dmaxM32', 32, 16, 512, 'MAX')
_mk_perbatch('perbatchmax', 8, 16, 512, 'MAX')
_mk_perbatch('perbatchmaxBig', 8, 32, 512, 'MAX')
_mk_perbatch('perbatchmaxM16big', 16, 32, 512, 'MAX')
_mk_perbatch('perbatchmin', 16, 16, 512, 'MIN')
_mk_perbatch('perslice3dM32', 32, 32, 512, 'SUM')
_mk_perbatch('perslice3dM64', 64, 16, 512, 'SUM')
_mk_perbatch('perslice3dM96', 96, 8, 512, 'SUM')

# perslice2d (64, 1024) full-slice == per-row SUM on a 2-D tensor
_mk_perrow('perslice2d', 64, 1024, 'SUM')

# ---- F6 mixed-reduction-op extraction ----
_mk_perrow_mixed('perrow_mixed_bigM', 128, 256)
_mk_mixmaxmin('mixmaxmin', K=8, N=4096)

# ---- F7 slab / chunk payload fusion ----
_mk_slab('eightslab', 8, 1024, scaled=True)
_mk_slab('batchedar8', 8, 1024, scaled=False)
_mk_slab('catsplitar', 2, 2048, scaled=False)
