"""
Llama transformer-block AR fusion (parallel-attention): Optimized implementation for AWS Trainium.

Generated by the LLM-guided algorithm evolution agent.
"""

import torch
import torch_xla.core.xla_model as xm
import torch_xla.runtime as xr

_WORLD = 32
_NUM_DEVICES = 16
_NUM_NODES = 1
_CORES_PER_DEVICE = 2

_rank = None
_world_size = None


def init_llama_block_ar():
    """Initialize rank/world info. Call once after dist.init_process_group."""
    global _rank, _world_size
    _rank = xr.global_ordinal()
    _world_size = xr.world_size()


# Agent-evolved algorithm
def evolved_llama_block(attn_partial, mlp_partial, rank, world_size,
                        num_devices, cores_per_device, xm, torch, num_nodes=1):
    """Agent: stack the two partials and AR them in a single dispatch."""
    stacked = torch.stack([attn_partial, mlp_partial], dim=0)
    ared = xm.all_reduce(xm.REDUCE_SUM, stacked)
    return [ared[0], ared[1]]


