"""
Uniform AllToAll (Fixed-Capacity MoE): Optimized implementation for AWS Trainium.

Generated by the LLM-guided algorithm evolution agent.
"""

import torch
import torch_xla.core.xla_model as xm
import torch_xla.runtime as xr

_WORLD = 32
_NUM_DEVICES = 16
_NUM_NODES = 1
_CORES_PER_DEVICE = 2

_rank = None
_world_size = None


def init_uniform_a2a():
    """Initialize rank/world info. Call once after dist.init_process_group."""
    global _rank, _world_size
    _rank = xr.global_ordinal()
    _world_size = xr.world_size()


# Agent-evolved algorithm
def evolved_uniform_a2a(input_tensor, chunk_size, rank, world_size,
                        num_devices, cores_per_device, xm, torch,
                        num_nodes=1):
    """Permute Ring: one collective_permute per distance."""
    total = world_size * chunk_size
    output = torch.zeros(total, device=input_tensor.device, dtype=input_tensor.dtype)
    output[rank * chunk_size:(rank + 1) * chunk_size] = \
        input_tensor[rank * chunk_size:(rank + 1) * chunk_size]
    for d in range(1, world_size):
        send_to = (rank + d) % world_size
        recv_from = (rank - d + world_size) % world_size
        send_chunk = input_tensor[send_to * chunk_size:(send_to + 1) * chunk_size]
        pairs = [(r, (r + d) % world_size) for r in range(world_size)]
        received = xm.collective_permute(send_chunk, pairs=pairs)
        output[recv_from * chunk_size:(recv_from + 1) * chunk_size] = received
    return output



# ================================================================
# Public API
# ================================================================

def uniform_a2a(input_tensor, chunk_size):
    """Uniform all-to-all using the agent-evolved algorithm."""
    if _rank is None:
        raise RuntimeError("Call init_uniform_a2a() first")
    return evolved_uniform_a2a(
        input_tensor, chunk_size, _rank, _world_size, _NUM_DEVICES,
        _CORES_PER_DEVICE, xm, torch, num_nodes=_NUM_NODES)

