"""
FSDP-style sharded weight prefetch with microbatching: Optimized implementation for AWS Trainium.

Generated by the LLM-guided algorithm evolution agent.
"""

import torch
import torch_xla.core.xla_model as xm
import torch_xla.runtime as xr

_WORLD = 32
_NUM_DEVICES = 16
_NUM_NODES = 1
_CORES_PER_DEVICE = 2

_rank = None
_world_size = None


def init_fsdp_prefetch():
    """Initialize rank/world info. Call once after dist.init_process_group."""
    global _rank, _world_size
    _rank = xr.global_ordinal()
    _world_size = xr.world_size()


# Agent-evolved algorithm
def evolved_fsdp_prefetch(shards, M, N_LAYERS, rank, world_size,
                          num_devices, cores_per_device, xm, torch, num_nodes=1):
    """Agent: bundle all M*N_LAYERS AGs into a single stacked AG."""
    flat = []
    for m in range(M):
        for L in range(N_LAYERS):
            flat.append(shards[m][L])
    stacked = torch.stack(flat, dim=0)                # (M*N_LAYERS, DM, shard_size)
    gathered = xm.all_gather(stacked, dim=-1)         # (M*N_LAYERS, DM, full_size)
    outs = []
    idx = 0
    for m in range(M):
        per_layer = []
        for L in range(N_LAYERS):
            per_layer.append(gathered[idx])
            idx += 1
        outs.append(per_layer)
    return outs


