"""
Ring Attention KV Distribution: Optimized implementation for AWS Trainium.

Generated by the LLM-guided algorithm evolution agent.
"""

import torch
import torch_xla.core.xla_model as xm
import torch_xla.runtime as xr

_WORLD = 32
_NUM_DEVICES = 16
_NUM_NODES = 1
_CORES_PER_DEVICE = 2

_rank = None
_world_size = None


def init_ring_kv():
    """Initialize rank/world info. Call once after dist.init_process_group."""
    global _rank, _world_size
    _rank = xr.global_ordinal()
    _world_size = xr.world_size()


# Agent-evolved algorithm
def evolved_ring_kv(kv_chunks, rank, world_size, num_devices,
                    cores_per_device, xm, torch, num_nodes=1):
    """Independent all_gather for each slot (one collective per slot)."""
    results = []
    for chunk in kv_chunks:
        gathered = xm.all_gather(chunk.unsqueeze(0), dim=0)
        results.append(gathered.view(-1))
    return results



# ================================================================
# Public API
# ================================================================

def ring_kv_gather(kv_chunks):
    """Gather all ranks' per-slot KV chunks using the agent-evolved algorithm.

    Args:
        kv_chunks: list of 1D tensors (typically [K_local, V_local]).

    Returns:
        list of 1D tensors, one per input slot, each holding all ranks' data
        for that slot concatenated in rank order.
    """
    if _rank is None:
        raise RuntimeError("Call init_ring_kv() first")
    return evolved_ring_kv(
        kv_chunks, _rank, _world_size, _NUM_DEVICES, _CORES_PER_DEVICE,
        xm, torch, num_nodes=_NUM_NODES)

