"""
trainium_alltoallv: Optimized AllToAllV for AWS Trainium

Drop-in replacement for torch all_to_all_single / MoE token dispatch.
Generated by the LLM-guided algorithm evolution agent.

Usage:
    from runtime import all_to_allv, init_alltoallv
    init_alltoallv()
    output = all_to_allv(input_tensor, send_counts)
"""

import torch
import torch_xla.core.xla_model as xm
import torch_xla.runtime as xr

_WORLD = 32
_NUM_DEVICES = 16
_NUM_NODES = 1
_CORES_PER_DEVICE = 2

_rank = None
_world_size = None


def init_alltoallv():
    """Initialize rank/world info. Call once after dist.init_process_group."""
    global _rank, _world_size
    _rank = xr.global_ordinal()
    _world_size = xr.world_size()


def compute_recv_counts(send_counts):
    """Exchange send_counts to derive recv_counts via all_gather."""
    device = xm.xla_device()
    t = torch.tensor(send_counts, device=device, dtype=torch.int32)
    gathered = xm.all_gather(t)
    gathered = gathered.view(_world_size, _world_size)
    return gathered[:, _rank].tolist()


# ================================================================
# Agent-evolved algorithm
# ================================================================

def evolved_alltoallv(input_tensor, send_counts, recv_counts, max_chunk,
                      rank, world_size, num_devices, cores_per_device,
                      xm, torch, num_nodes=1):
    pack_size = world_size * max_chunk

    packed = torch.zeros(pack_size, device=input_tensor.device,
                         dtype=input_tensor.dtype)
    send_off = 0
    for i in range(world_size):
        sc = send_counts[i]
        if sc > 0:
            packed[i * max_chunk:i * max_chunk + sc] = \
                input_tensor[send_off:send_off + sc]
        send_off += sc

    gathered = xm.all_gather(packed.unsqueeze(0), dim=0).view(-1)

    flat_idx = []
    for src in range(world_size):
        count = recv_counts[src]
        base = src * pack_size + rank * max_chunk
        flat_idx.extend(range(base, base + count))

    idx_tensor = torch.tensor(flat_idx, device=input_tensor.device,
                              dtype=torch.long)
    return torch.index_select(gathered, 0, idx_tensor)


# ================================================================
# Public API
# ================================================================

def all_to_allv(x, send_counts, recv_counts=None, max_chunk=None):
    """
    Perform AllToAllV using the agent-evolved algorithm.

    Args:
        x: 1D input tensor (concatenated send data for all ranks)
        send_counts: list[int] of length world_size
        recv_counts: list[int] or None (computed via all_gather if None)
        max_chunk: int or None (auto-computed if None)

    Returns:
        1D tensor with received data concatenated in source-rank order
    """
    if _rank is None:
        raise RuntimeError("Call init_alltoallv() first")

    if recv_counts is None:
        recv_counts = compute_recv_counts(send_counts)

    if max_chunk is None:
        max_chunk = max(max(send_counts), max(recv_counts), 1)

    return evolved_alltoallv(
        x, send_counts, recv_counts, max_chunk,
        _rank, _world_size, _NUM_DEVICES, _CORES_PER_DEVICE,
        xm, torch, num_nodes=_NUM_NODES)


def alltoallv(x, world_size, max_chunk):
    """Pre-packed uniform AllToAllV (backward-compat API).

    Equivalent to all_to_allv with send_counts=recv_counts=[max_chunk]*ws,
    but uses a fixed all_gather + per-source slice + cat path that does not
    build a host-side index tensor on every call (cheaper for the uniform
    case used by typical MoE token dispatch).
    """
    if _rank is None:
        raise RuntimeError("Call init_alltoallv() first")
    rank = _rank
    ws = world_size
    mc = max_chunk
    gathered = xm.all_gather(x.unsqueeze(0), dim=0).view(ws, -1)
    chunks = []
    for src in range(ws):
        chunks.append(gathered[src, rank * mc:rank * mc + mc])
    return torch.cat(chunks, dim=0)
