"""
TP MLP with microbatching: Optimized implementation for AWS Trainium.

Generated by the LLM-guided algorithm evolution agent.
"""

import torch
import torch_xla.core.xla_model as xm
import torch_xla.runtime as xr

_WORLD = 224
_NUM_DEVICES = 112
_NUM_NODES = 7
_CORES_PER_DEVICE = 2

_rank = None
_world_size = None


def init_tp_mlp():
    """Initialize rank/world info. Call once after dist.init_process_group."""
    global _rank, _world_size
    _rank = xr.global_ordinal()
    _world_size = xr.world_size()


# Agent-evolved algorithm
def evolved_tp_mlp(partials, M, N_LAYERS, rank, world_size,
                   num_devices, cores_per_device, xm, torch, num_nodes=1):
    """Full flatten single AR: Concatenate all M*N_LAYERS partials into one 
    contiguous tensor, issue a single all-reduce, then slice/reshape back to 
    [M][N_LAYERS] structure."""
    
    # Step 1: Flatten all partials into a single contiguous tensor
    # We need to preserve shapes for later reconstruction
    shapes = []
    flattened_parts = []
    
    for m in range(M):
        for L in range(N_LAYERS):
            shapes.append(partials[m][L].shape)
            flattened_parts.append(partials[m][L].flatten())
    
    # Concatenate all flattened tensors into one
    stacked = torch.cat(flattened_parts, dim=0)
    
    # Step 2: Single all-reduce operation
    reduced = xm.all_reduce(xm.REDUCE_SUM, stacked)
    
    # Step 3: Slice and reshape back to [M][N_LAYERS] structure
    outs = []
    offset = 0
    
    for m in range(M):
        per_layer = []
        for L in range(N_LAYERS):
            shape = shapes[m * N_LAYERS + L]
            numel = 1
            for dim in shape:
                numel *= dim
            
            # Extract the slice corresponding to this (m, L) pair
            slice_tensor = reduced[offset:offset + numel]
            # Reshape back to original shape
            reshaped = slice_tensor.reshape(shape)
            per_layer.append(reshaped)
            
            offset += numel
        
        outs.append(per_layer)
    
    return outs

