"""
Pipeline-parallel cross-stage send/recv: Optimized implementation for AWS Trainium.

Generated by the LLM-guided algorithm evolution agent.
"""

import torch
import torch_xla.core.xla_model as xm
import torch_xla.runtime as xr

_WORLD = 224
_NUM_DEVICES = 112
_NUM_NODES = 7
_CORES_PER_DEVICE = 2

_rank = None
_world_size = None


def init_pp_send_recv():
    """Initialize rank/world info. Call once after dist.init_process_group."""
    global _rank, _world_size
    _rank = xr.global_ordinal()
    _world_size = xr.world_size()


# Agent-evolved algorithm
def evolved_pp_send_recv(activations, src_stage, half, M, rank, world_size,
                         num_devices, cores_per_device, xm, torch, num_nodes=1):
    """Single stacked all-reduce dispatch: stack M microbatches, one collective, then unstack."""
    stage = 0 if rank < half else 1
    pair_id = rank if stage == 0 else rank - half
    
    # Get activation properties from first microbatch
    a0 = activations[0]
    dtype = a0.dtype
    act_shape = a0.shape  # (B, S, DM)
    
    # Stack all M microbatches into a single tensor of shape (half, M, B, S, DM)
    # Initialize buffer for all microbatches
    stacked_buf = torch.zeros(half, M, *act_shape, dtype=dtype, device=a0.device)
    
    # If this rank is in the source stage, populate its slot with all M microbatches
    if stage == src_stage:
        for m in range(M):
            stacked_buf[pair_id, m] = activations[m]
    
    # Perform single all-reduce across all microbatches at once
    stacked_ared = xm.all_reduce(xm.REDUCE_SUM, stacked_buf)
    
    # Unstack into M separate tensors
    outs = []
    for m in range(M):
        outs.append(stacked_ared[pair_id, m])
    
    return outs

