"""
Replicated-Gradient AllReduce: Optimized implementation for AWS Trainium.

Generated by the LLM-guided algorithm evolution agent.
"""

import torch
import torch_xla.core.xla_model as xm
import torch_xla.runtime as xr

_WORLD = 224
_NUM_DEVICES = 112
_NUM_NODES = 7
_CORES_PER_DEVICE = 2

_rank = None
_world_size = None


def init_grad_ar():
    """Initialize rank/world info. Call once after dist.init_process_group."""
    global _rank, _world_size
    _rank = xr.global_ordinal()
    _world_size = xr.world_size()


# Agent-evolved algorithm
def evolved_grad_ar(rep_grads, rank, world_size, num_devices,
                    cores_per_device, xm, torch, num_nodes=1):
    """Concat -> single AR -> split. Loses on Trainium due to cat overhead."""
    inv = 1.0 / world_size
    shapes = [g.shape for g in rep_grads]
    flat = torch.cat([g.reshape(-1) for g in rep_grads])
    flat = xm.all_reduce(xm.REDUCE_SUM, flat) * inv
    out = []
    offs = 0
    for sh in shapes:
        n = 1
        for d in sh:
            n *= d
        out.append(flat[offs:offs + n].reshape(sh))
        offs += n
    return out



# ================================================================
# Public API
# ================================================================

def grad_ar_sync(rep_params, world_size=None):
    """All-reduce per-tensor on a list of replicated parameters' gradients,
    in place, dividing by world_size for a mean.
    """
    if _rank is None:
        raise RuntimeError("Call init_grad_ar() first")
    ws = world_size if world_size is not None else _world_size
    grads = [p.grad.data for p in rep_params if p.grad is not None]
    if not grads:
        return
    out = evolved_grad_ar(
        grads, _rank, ws, _NUM_DEVICES, _CORES_PER_DEVICE,
        xm, torch, num_nodes=_NUM_NODES)
    i = 0
    for p in rep_params:
        if p.grad is not None:
            p.grad.data = out[i]
            i += 1

