"""
Uniform AllToAll (Fixed-Capacity MoE): Optimized implementation for AWS Trainium.

Generated by the LLM-guided algorithm evolution agent.
"""

import torch
import torch_xla.core.xla_model as xm
import torch_xla.runtime as xr

_WORLD = 32
_NUM_DEVICES = 16
_NUM_NODES = 1
_CORES_PER_DEVICE = 2

_rank = None
_world_size = None


def init_uniform_a2a():
    """Initialize rank/world info. Call once after dist.init_process_group."""
    global _rank, _world_size
    _rank = xr.global_ordinal()
    _world_size = xr.world_size()


# Agent-evolved algorithm
def evolved_uniform_a2a(input_tensor, chunk_size, rank, world_size,
                        num_devices, cores_per_device, xm, torch,
                        num_nodes=1):
    """AllGather + per-source slice loop."""
    gathered = xm.all_gather(input_tensor.unsqueeze(0), dim=0)
    flat = gathered.view(world_size, -1)
    chunks = []
    for src in range(world_size):
        chunks.append(flat[src, rank * chunk_size:(rank + 1) * chunk_size])
    return torch.cat(chunks, dim=0)



# ================================================================
# Public API
# ================================================================

def uniform_a2a(input_tensor, chunk_size):
    """Uniform all-to-all using the agent-evolved algorithm."""
    if _rank is None:
        raise RuntimeError("Call init_uniform_a2a() first")
    return evolved_uniform_a2a(
        input_tensor, chunk_size, _rank, _world_size, _NUM_DEVICES,
        _CORES_PER_DEVICE, xm, torch, num_nodes=_NUM_NODES)

