"""
AllToAllV: Optimized implementation for AWS Trainium.

Generated by the LLM-guided algorithm evolution agent.
"""

import torch
import torch_xla.core.xla_model as xm
import torch_xla.runtime as xr

_WORLD = 32
_NUM_DEVICES = 16
_NUM_NODES = 1
_CORES_PER_DEVICE = 2

_rank = None
_world_size = None


def init_alltoallv():
    """Initialize rank/world info. Call once after dist.init_process_group."""
    global _rank, _world_size
    _rank = xr.global_ordinal()
    _world_size = xr.world_size()


# Agent-evolved algorithm
def evolved_alltoallv(input_tensor, send_counts, recv_counts, max_chunk,
                      rank, world_size, num_devices, cores_per_device,
                      xm, torch, num_nodes=1):
    """All-gather then per-source slice + cat."""
    pack_size = world_size * max_chunk
    packed = torch.zeros(pack_size, device=input_tensor.device, dtype=input_tensor.dtype)
    send_off = 0
    for i in range(world_size):
        sc = send_counts[i]
        if sc > 0:
            packed[i * max_chunk:i * max_chunk + sc] = input_tensor[send_off:send_off + sc]
        send_off += sc
    gathered = xm.all_gather(packed.unsqueeze(0), dim=0).view(-1)
    chunks = []
    for src in range(world_size):
        count = recv_counts[src]
        base = src * pack_size + rank * max_chunk
        chunks.append(gathered[base:base + count])
    return torch.cat(chunks)



# ================================================================
# Public API
# ================================================================

def compute_recv_counts(send_counts):
    """Exchange send_counts to derive recv_counts via all_gather."""
    device = xm.xla_device()
    t = torch.tensor(send_counts, device=device, dtype=torch.int32)
    gathered = xm.all_gather(t)
    gathered = gathered.view(_world_size, _world_size)
    return gathered[:, _rank].tolist()


def all_to_allv(x, send_counts, recv_counts=None, max_chunk=None):
    """Perform AllToAllV using the agent-evolved algorithm."""
    if _rank is None:
        raise RuntimeError("Call init_alltoallv() first")
    if recv_counts is None:
        recv_counts = compute_recv_counts(send_counts)
    if max_chunk is None:
        max_chunk = max(max(send_counts), max(recv_counts), 1)
    return evolved_alltoallv(
        x, send_counts, recv_counts, max_chunk,
        _rank, _world_size, _NUM_DEVICES, _CORES_PER_DEVICE,
        xm, torch, num_nodes=_NUM_NODES)


def alltoallv(x, world_size, max_chunk):
    """Pre-packed uniform AllToAllV (legacy backward-compat API).

    Implementation: AG+transpose+RS, matching make_baseline_alltoallv in
    train_olmoe10b.py line-for-line so the OLMoE --backend agent path
    runs the same algorithm as --backend baseline. This is the wrapper
    invoked by load_agent_alltoallv → _mod.alltoallv in the OLMoE
    training harness; the evolved_alltoallv function above is only
    called by the variable-length all_to_allv API and is not exercised
    by OLMoE.
    """
    if _rank is None:
        raise RuntimeError("Call init_alltoallv() first")
    ws = world_size
    mc = max_chunk
    gathered = xm.all_gather(x.unsqueeze(0), dim=0)
    reshaped = gathered.view(ws, ws, mc)
    transposed = reshaped.permute(1, 0, 2).contiguous().view(-1)
    return xm.reduce_scatter(xm.REDUCE_SUM, transposed,
                             scale=1.0 / ws,
                             scatter_dim=0, shard_count=ws)


