"""
Replicated-Gradient AllReduce: Optimized implementation for AWS Trainium.

Generated by the LLM-guided algorithm evolution agent.
"""

import torch
import torch_xla.core.xla_model as xm
import torch_xla.runtime as xr

_WORLD = 224
_NUM_DEVICES = 112
_NUM_NODES = 7
_CORES_PER_DEVICE = 2

_rank = None
_world_size = None


def init_grad_ar():
    """Initialize rank/world info. Call once after dist.init_process_group."""
    global _rank, _world_size
    _rank = xr.global_ordinal()
    _world_size = xr.world_size()


# Agent-evolved algorithm
def evolved_grad_ar(rep_grads, rank, world_size, num_devices,
                    cores_per_device, xm, torch, num_nodes=1):
    if not rep_grads:
        return []
    if world_size == 1:
        return list(rep_grads)
    inv = 1.0 / world_size
    n = len(rep_grads)

    if n == 1:
        return [xm.all_reduce(xm.REDUCE_SUM, rep_grads[0]) * inv]

    # Compute sizes in Python.
    sizes = []
    total_bytes = 0
    for g in rep_grads:
        b = g.numel() * g.element_size()
        sizes.append(b)
        total_bytes += b

    chunk_bytes = 64 * 1024 * 1024

    # Bucket into as few groups as possible under byte cap.
    buckets = []
    cur_idx, cur_bytes = [], 0
    for i in range(n):
        b = sizes[i]
        if cur_idx and cur_bytes + b > chunk_bytes:
            buckets.append(cur_idx)
            cur_idx, cur_bytes = [], 0
        cur_idx.append(i)
        cur_bytes += b
    if cur_idx:
        buckets.append(cur_idx)

    out = [None] * n
    for idxs in buckets:
        if len(idxs) == 1:
            i = idxs[0]
            out[i] = xm.all_reduce(xm.REDUCE_SUM, rep_grads[i]) * inv
            continue

        # Inputs are 1D per spec — skip reshape(-1).
        # Build numels for split.
        numels = [rep_grads[i].numel() for i in idxs]
        shapes = [rep_grads[i].shape for i in idxs]

        # Ensure 1D for cat. If already 1D (per spec), pass directly.
        tensors_to_cat = []
        need_reshape = False
        for i in idxs:
            t = rep_grads[i]
            if t.dim() != 1:
                t = t.reshape(-1)
                need_reshape = True
            tensors_to_cat.append(t)

        flat = torch.cat(tensors_to_cat)
        flat = xm.all_reduce(xm.REDUCE_SUM, flat) * inv
        parts = torch.split(flat, numels)
        for j, i in enumerate(idxs):
            p = parts[j]
            if p.shape != shapes[j]:
                p = p.reshape(shapes[j])
            out[i] = p
    return out


# ================================================================
# Public API
# ================================================================

def grad_ar_sync(rep_params, world_size=None):
    """All-reduce per-tensor on a list of replicated parameters' gradients,
    in place, dividing by world_size for a mean.
    """
    if _rank is None:
        raise RuntimeError("Call init_grad_ar() first")
    ws = world_size if world_size is not None else _world_size
    grads = [p.grad.data for p in rep_params if p.grad is not None]
    if not grads:
        return
    out = evolved_grad_ar(
        grads, _rank, ws, _NUM_DEVICES, _CORES_PER_DEVICE,
        xm, torch, num_nodes=_NUM_NODES)
    i = 0
    for p in rep_params:
        if p.grad is not None:
            p.grad.data = out[i]
            i += 1

