"""
Pipeline-parallel cross-stage send/recv: Optimized implementation for AWS Trainium.

Generated by the LLM-guided algorithm evolution agent.
"""

import torch
import torch_xla.core.xla_model as xm
import torch_xla.runtime as xr

_WORLD = 32
_NUM_DEVICES = 16
_NUM_NODES = 1
_CORES_PER_DEVICE = 2

_rank = None
_world_size = None


def init_pp_send_recv():
    """Initialize rank/world info. Call once after dist.init_process_group."""
    global _rank, _world_size
    _rank = xr.global_ordinal()
    _world_size = xr.world_size()


# Agent-evolved algorithm
def evolved_pp_send_recv(activations, src_stage, half, M, rank, world_size,
                         num_devices, cores_per_device, xm, torch, num_nodes=1):
    """Agent: bundle M microbatches' activations into one AR over a
    (half, M, *act_shape) buffer."""
    stage = 0 if rank < half else 1
    pair_id = rank if stage == 0 else rank - half
    stacked = torch.stack(activations, dim=0)            # (M, *act_shape)
    buf = torch.zeros(half, *stacked.shape, dtype=stacked.dtype)
    if stage == src_stage:
        buf[pair_id] = stacked
    ared = xm.all_reduce(xm.REDUCE_SUM, buf)
    return [ared[pair_id, m] for m in range(M)]


