"""
Generate Python wrapper module for AllToAllV runtime.

Wraps the agent's evolved algorithm into a runtime module with a clean
public API: all_to_allv(input, send_counts).

The evolved code defines `evolved_alltoallv()` with the sandbox signature
(xm, torch passed as parameters).  This module rewrites it to use real
imports so it can be called directly in training code.

Usage in training code:
    from runtime import all_to_allv, init_alltoallv
    init_alltoallv()
    output = all_to_allv(input_tensor, send_counts)
"""

import re
import textwrap


def emit_python_wrapper(best_template, best_params, world=32, num_devices=16,
                        num_nodes=1):
    """
    Generate the Python runtime module from the agent's best algorithm.

    The evolved code (in best_params["evolved_code"]) is the actual algorithm
    the LLM discovered.  We wrap it with imports and a public API.

    If no evolved code is available (schedule-based templates like permute_ring),
    we emit a minimal wrapper that calls the template via XLA ops.
    """
    evolved_code = best_params.get("evolved_code")

    if evolved_code:
        return _emit_evolved_runtime(evolved_code, world, num_devices, num_nodes)

    # Schedule-based templates (permute_ring, hierarchical, etc.) don't have
    # evolved code — emit a stub that notes the template name and params.
    return _emit_schedule_runtime(best_template, best_params, world,
                                  num_devices, num_nodes)


def _emit_evolved_runtime(evolved_code, world=32, num_devices=16, num_nodes=1):
    """Wrap the agent's evolved algorithm into a runtime module.

    The evolved function uses the sandbox signature:
        evolved_alltoallv(input_tensor, send_counts, recv_counts, max_chunk,
                          rank, world_size, num_devices, cores_per_device,
                          xm, torch, num_nodes=1)

    We emit a module that imports real xm/torch and delegates to it.
    """
    return f'''\
"""
trainium_alltoallv: Optimized AllToAllV for AWS Trainium

Drop-in replacement for torch all_to_all_single / MoE token dispatch.
Generated by the LLM-guided algorithm evolution agent.

Usage:
    from runtime import all_to_allv, init_alltoallv
    init_alltoallv()
    output = all_to_allv(input_tensor, send_counts)
"""

import torch
import torch_xla.core.xla_model as xm
import torch_xla.runtime as xr

_WORLD = {world}
_NUM_DEVICES = {num_devices}
_NUM_NODES = {num_nodes}
_CORES_PER_DEVICE = 2

_rank = None
_world_size = None


def init_alltoallv():
    """Initialize rank/world info. Call once after dist.init_process_group."""
    global _rank, _world_size
    _rank = xr.global_ordinal()
    _world_size = xr.world_size()


def compute_recv_counts(send_counts):
    """Exchange send_counts to derive recv_counts via all_gather."""
    device = xm.xla_device()
    t = torch.tensor(send_counts, device=device, dtype=torch.int32)
    gathered = xm.all_gather(t)
    gathered = gathered.view(_world_size, _world_size)
    return gathered[:, _rank].tolist()


# ================================================================
# Agent-evolved algorithm
# ================================================================

{evolved_code.strip()}


# ================================================================
# Public API
# ================================================================

def all_to_allv(x, send_counts, recv_counts=None, max_chunk=None):
    """
    Perform AllToAllV using the agent-evolved algorithm.

    Args:
        x: 1D input tensor (concatenated send data for all ranks)
        send_counts: list[int] of length world_size
        recv_counts: list[int] or None (computed via all_gather if None)
        max_chunk: int or None (auto-computed if None)

    Returns:
        1D tensor with received data concatenated in source-rank order
    """
    if _rank is None:
        raise RuntimeError("Call init_alltoallv() first")

    if recv_counts is None:
        recv_counts = compute_recv_counts(send_counts)

    if max_chunk is None:
        max_chunk = max(max(send_counts), max(recv_counts), 1)

    return evolved_alltoallv(
        x, send_counts, recv_counts, max_chunk,
        _rank, _world_size, _NUM_DEVICES, _CORES_PER_DEVICE,
        xm, torch, num_nodes=_NUM_NODES)
'''


def _emit_schedule_runtime(template_name, params, world=32, num_devices=16,
                            num_nodes=1):
    """Emit a minimal runtime for schedule-based templates (no evolved code).

    This is a fallback for when the winning template is a parameterized
    schedule (like permute_ring) rather than an evolved algorithm.
    """
    schedule = params.get("schedule", params.get("inter_schedule", []))
    return f'''\
"""
trainium_alltoallv: AllToAllV for AWS Trainium

Generated by search agent. Template: {template_name}
No evolved algorithm — this is a schedule-based template.

Usage:
    from runtime import all_to_allv, init_alltoallv
    init_alltoallv()
    output = all_to_allv(input_tensor, send_counts)
"""

import torch
import torch_xla.core.xla_model as xm
import torch_xla.runtime as xr

_WORLD = {world}
_NUM_DEVICES = {num_devices}
_NUM_NODES = {num_nodes}
_SCHEDULE = {schedule}

_rank = None
_world_size = None


def init_alltoallv():
    """Initialize rank/world info. Call once after dist.init_process_group."""
    global _rank, _world_size
    _rank = xr.global_ordinal()
    _world_size = xr.world_size()


def compute_recv_counts(send_counts):
    """Exchange send_counts to derive recv_counts via all_gather."""
    device = xm.xla_device()
    t = torch.tensor(send_counts, device=device, dtype=torch.int32)
    gathered = xm.all_gather(t)
    gathered = gathered.view(_world_size, _world_size)
    return gathered[:, _rank].tolist()


def all_to_allv(x, send_counts, recv_counts=None, max_chunk=None):
    """
    Perform AllToAllV using {template_name} schedule.

    This is a schedule-based template, not an evolved algorithm.
    For optimal performance, run the search agent with --hw-eval to
    discover the best algorithm for your hardware.
    """
    if _rank is None:
        raise RuntimeError("Call init_alltoallv() first")

    if recv_counts is None:
        recv_counts = compute_recv_counts(send_counts)

    if max_chunk is None:
        max_chunk = max(max(send_counts), max(recv_counts), 1)

    # Permute-ring: send to each destination via collective_permute
    chunks = []
    for dist in _SCHEDULE:
        dst = (_rank + dist) % _world_size
        src = (_rank - dist) % _world_size

        send_offset = sum(send_counts[:dst])
        sc = send_counts[dst]
        padded = torch.zeros(max_chunk, device=x.device, dtype=x.dtype)
        if sc > 0:
            padded[:sc] = x[send_offset:send_offset + sc]

        received = xm.collective_permute(padded,
            pairs=[[(r, (r + dist) % _world_size) for r in range(_world_size)]])

        rc = recv_counts[src]
        if rc > 0:
            chunks.append(received[:rc])

    # Self-send
    self_offset = sum(send_counts[:_rank])
    sc = send_counts[_rank]
    if sc > 0:
        chunks.insert(_rank, x[self_offset:self_offset + sc])
    else:
        chunks.insert(_rank, torch.zeros(0, device=x.device, dtype=x.dtype))

    return torch.cat(chunks)
'''
